### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by haoranD** [byzhaoAI/BM2CP#1]
Hi,

I wanted to express my gratitude for the valuable work you've been doing.

I am eagerly looking forward to the release of the code. Could you please provide an estimated time for when it will be made available?

Thanks a lot.

Best,

**Comment by byzhaoAI** [comment]
Hi, @haoranD. We plan to organize and then release the first version in this month (Nov.). Otherwise it will be no later than next month (Dec.).

**Comment by deyang2000** [comment]
I can't wait to see your awesome work.

**Comment by byzhaoAI** [comment]
Hi, @haoranD and @deyang2000 . We have uploaded the first version of BM2CP. Thank you for the great support!

**Comment by haoranD** [comment]
@byzhaoAI thanks a lot

**Comment by deyang2000** [comment]
@byzhaoAI Thank you for your outstanding work.
