### ISSUE TITLE
Questions about preference maps

### ISSUE THREAD

**Issue by nicezzl** [byzhaoAI/BM2CP#13]
The preference map is actually composed of feature values. The purpose of the classification head is to distinguish between the target and the background, and the value is between 0 and 1. I don't quite understand why the feature values ​​are compared with the results of the classification head. It feels strange? Is this for the purpose, or is there a reference to other papers?

**Comment by nicezzl** [comment]
I understand now, thanks.

**Comment by byzhaoAI** [comment]
My pleasure! Welcome for further discussion.
