### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Lesliewsq** [byzhaoAI/BM2CP#2]
When I train, the CPU usage is very high. Is this normal?   
![1701933630108](https://github.com/byzhaoAI/BM2CP/assets/81459252/304bdf40-b633-4b10-94fb-43c0481340ce)
GPU memory
![1701934651869](https://github.com/byzhaoAI/BM2CP/assets/81459252/74ad8217-ecc6-48aa-a8dd-ed79b7bdee84)

**Comment by byzhaoAI** [comment]
Hi, @Lesliewsq . This might be normal. The main framework of code is succeeded from [OpenCOOD](https://githubfast.com/MediaBrain-SJTU/Where2comm) and [Where2comm](https://githubfast.com/MediaBrain-SJTU/Where2comm).

**Comment by Lesliewsq** [comment]
Thanks for the reply. How should I do if I want to test this model on OPV2V dataset？

**Comment by byzhaoAI** [comment]
Currently we have not released the code to fit OPV2V dataset, which we are organizing and plan to release cprrespoding version in the short future. 

If you want to apply it for OPV2V dataset right now, we suggest to use a little incomplete version by directly copying [bm2cp model](https://githubfast.com/byzhaoAI/BM2CP/blob/master/opencood/models/point_pillar_bm2cp.py) and its [submodules](https://githubfast.com/byzhaoAI/BM2CP/tree/master/opencood/models/bm2cp_modules) into correspoding [OpenCOOD model ](https://github.com/DerrickXuNu/OpenCOOD/tree/main/opencood/models) path. 

You need to delete line103-118, line124-142, line147, line150, and add line151(replace _nodepth_x_ by _final_depth_) in "sensor_blocks.py" to use fully _prediction_ strategy in camera branch.

**Comment by Lesliewsq** [comment]
If I want to train BM2CP on OPV2V dataset，how should I change the config file

**Comment by byzhaoAI** [comment]
You can take yaml file in OpenCOOD as the base file, and change the setting of model based on code in our codebase.

**Comment by Lesliewsq** [comment]
Thank you for the reply. I have tried to train BM2CP on OPV2V dataset，but I found that the cache has been increasing. When the first epoch of training is completed and the evaluation is started, an access out-of-bound error will be reported (I guess there is not enough memory). 

![1705315998543](https://github.com/byzhaoAI/BM2CP/assets/81459252/02886659-d0b6-46a9-82ad-68b7dfa189a2)
The picture above shows the memory status of my computer under normal conditions. 

When I train on DAIR-V2X , the cache will increase to more than 40 GB. When I train on OPV2V , the cache will increase to more than 100 GB , and then the out-of-bound error occurs. My computer has about 125GB memory.  Do you have some good suggestions ?

**Comment by byzhaoAI** [comment]
Indeed, I have the same problem when training on OPV2V. In fact, I have to stop and rerun the code many times to finish the training. Now I'm trying to build the environment under my database to avoid this issue.

By the way, [CoAlign](https://github.com/yifanlu0227/CoAlign) dose not have the out-of-bound problem, but the performance is not consistent with that on OpenCOOD.

**Comment by Lesliewsq** [comment]
Is there a solution to this problem?

**Comment by Lesliewsq** [comment]
So happy to hear the good news. That's awesome.
