### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by 2017904315** [byzhaoAI/BM2CP#3]
Hello, thank you very much for your excellent work. Based on your code, I noticed that even when training with the command：
`python -m torch.distributed.launch --nproc_per_node=4  --use_env tools/train.py --hypes_yaml hypes_yaml/dair-v2x/dair_bm2cp.yaml`
on four RTX 3090 GPUs, it takes nearly 5 hours for one epoch. 

I would like to confirm if our multi-GPU training command is correct. Additionally, could you please share the hardware specifications you used for training and an estimate of how long it took to complete 50 epochs during your training? Thank you.

**Comment by byzhaoAI** [comment]
Hi, @2017904315. I have ever run the model on 1080Ti and RTX 4090, the running time for 20 epochs are no more than 3 days and 1.5 days, respectively. According to your description, it is possibly normal, and the bottleneck may come from the CPU.

**Comment by 2017904315** [comment]
@byzhaoAI Thank you for your reply. May I ask what model of CPU you use for the tasks? The CPU we use in our machine is Intel 5320.

**Comment by byzhaoAI** [comment]
I received your email and have replied this question, please check.

Distributed training is not used when I conduct experiments.

**Comment by 2017904315** [comment]
Thanks for your reply.
