### ISSUE TITLE
code update

### ISSUE THREAD

**Issue by Hongbo123467** [byzhaoAI/BM2CP#4]
您好，我之前工作基于第一版代码，现在第二版的代码直接覆盖了第一版的，我不知道相比第一版，第二版改动了哪些部分，可以明确一下吗，谢谢。

**Comment by byzhaoAI** [comment]
@Hongbo123467，我在README.md里面有添加Updates的说明，第二版更新的内容有：
        1. 添加代码支持OPV2V数据集；
        2. 添加代码支持SCOPE(ICCV2023)方法；
        3. 修复姿态误差(pose error)存在情况下，方法在DAIR-V2X数据集性能表现异常的错误。
