### ISSUE TITLE
ImportError: cannot import name 'sensor_transformation_utils' from 'opencood.utils'

### ISSUE THREAD

**Issue by fengxueguiren** [byzhaoAI/BM2CP#5]
您好，最新版本的代码出现下面的错误，配置文件是`hypes_yaml/opv2v/opv2v_bm2cp.yaml`，数据集是OPV2V。
·
```shell
ImportError: cannot import name 'sensor_transformation_utils' from 'opencood.utils' (/xxx/BM2CP/opencood/utils/__init__.py)
```

**Comment by byzhaoAI** [comment]
感谢您的关注，代码库已更新

**Comment by bao123b** [comment]
> 您好，最新版本的代码出现下面的错误，配置文件是，数据集是OPV2V。`hypes_yaml/opv2v/opv2v_bm2cp.yaml` ·
> 
> ```shell
> ImportError: cannot import name 'sensor_transformation_utils' from 'opencood.utils' (/xxx/BM2CP/opencood/utils/__init__.py)
> ```

你好，请问这个问题解决了吗？我目前也遇到了这个报错。

**Comment by byzhaoAI** [comment]
最新的代码已包含 opencood.utils.sensor_transformation_utils.py

**Comment by bao123b** [comment]
> 最新的代码已包含 opencood.utils.sensor_transformation_utils.py

好的，非常感谢您的解答。
