### ISSUE TITLE
Dairv2x cannot be trained using early fusion. 

### ISSUE THREAD

**Issue by wanghangege** [byzhaoAI/BM2CP#6]
Dairv2x cannot be trained using early fusion，because there is no funcution “collate_batch_train” in "early_fusion_dataset.py"
Is there a solution?

**Comment by byzhaoAI** [comment]
You can refer to the function "collate_batch_train" in "opencood/data_utils/datasets/dair/basedataset.py"

**Comment by wanghangege** [comment]
> You can refer to the function "collate_batch_train" in "opencood/data_utils/datasets/dair/basedataset.py"

thanks
