### ISSUE TITLE
"SCOPE" MAP is extremely low

### ISSUE THREAD

**Issue by wanghangege** [byzhaoAI/BM2CP#8]
"SCOPE" MAP is extremely low. Have you tested the MAP of the code on DAIR-V2X?The results of my test are as follows:
[Epoch: 30 | AP @0.3: 0.4229 | AP @0.5: 0.3183 | AP @0.7: 0.0703 | comm_rate: 0.000000](url)

**Comment by byzhaoAI** [comment]
We do not compare with SCOPE in our paper. 

On the other hand, I only embed its official code to my project. You can try to reimplement it using their official code, or ask this question to the author of SCOPE.
