### ISSUE TITLE
使用OPV2V数据集报错的问题

### ISSUE THREAD

**Issue by Wesley-wsj** [byzhaoAI/BM2CP#9]
![image](https://github.com/byzhaoAI/BM2CP/assets/152406043/be8f46b3-763c-4293-aa5a-00d4de2d03ea)
您好，我使用opv2v数据集训练时遇到这个问题，原因是opv2v数据集里边大部分场景每辆车有4个camera，而2021_09_09_13_20_58这个场景中每个车辆只有3个camera，在yaml配置文件里的摄像头数量是设置为4的，请问您是怎么处理这种情况的呢？

**Comment by byzhaoAI** [comment]
OPV2V应该没有这个场景吧，没有遇到这个问题。

V2XSet确实会报缺少camera的错误，个人观点有如下两种处理方式：
1、不考虑缺少的camera，模型是仍然能够适应只有3个camera的情况的（需要修改部分处理数据集的代码）；
2、该场景不参与训练/评估/测试。

**Comment by Wesley-wsj** [comment]
好的，非常感谢您的解答！

**Comment by ruiiu** [comment]
我也遇到了同样的问题，请问这个问题您最后具体是怎么解决的呢？需要具体在code里面哪里改一下呢，麻烦能方便指出来吗？

**Comment by byzhaoAI** [comment]
在opv2v里面没有这个问题

如果你在其他数据集出现这种情况，可以在

opencood/data_utils/datasets/opv2v/lidar_camera_intermediate_fusion_dataset_v2.py

第443行加载相机图片时提前进行判定是否存在该文件，不存在则直接跳过
